### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by SidTheEngineer** [daniel1993c/pwp-capstones#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4
* _Comment(s):_ Nice job! The included code runs without any errors ✅ 
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order. ✅ 
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. ✅ 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4
* _Comment(s):_ Good work overall taking advantage of Python language features like dicts, math functions, and string functions such as `format()`. ✅ 

### Criteria 5: Produces Accurate Output
* _Score Level:_ 3/4
* _Comment(s):_ One place we'll want to adjust to get more accurate output is in the `get_average_sentence_length` method. We'll want to add a check that makes sure our sentence isn't empty (i.e. just spaces). We can do this by adding a check at the top of the `for` loop:

```Python
for sentence in sentences_in_text:
    if not sentence.strip():
        continue
    sentence_lengths.append(len(sentence.split(" ")))
avg_length = sum(sentence_lengths) / len(sentence_lengths)
```

**Comment by daniel1993c** [comment]
Thanks for the feedback! I plan to continue to improve on this and make it better. I'm happy with being on the right track.
